version: '3.8'

services:
  mysql_finanzas:
    image: mysql:8.3
    container_name: mysql_finanzas_personales
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: finanzas_personales
      MYSQL_USER: alverik
      MYSQL_PASSWORD: alverik
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./finanzas_personales_db.sql:/docker-entrypoint-initdb.d/finanzas_personales_db.sql
    restart: unless-stopped

volumes:
  mysql_data: